[package]
name = "vim_settings"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/vim_settings.rs"

[dependencies]
anyhow.workspace = true
collections.workspace = true
gpui.workspace = true
settings.workspace = true
serde.workspace = true
schemars.workspace = true
